---
- name: Generate FNE configuration from template
  ansible.builtin.template:
    src: templates/configs/configFNE.yml.j2
    dest: /opt/{{ dvm_folder }}/configs/configFNE.yml

- name: Load talkgroup configuration data
  ansible.builtin.include_vars:
    file: "{{ tg_config_file }}"
    name: talkgroup_data

- name: Generate talkgroup configuration from template
  ansible.builtin.template:
    src: templates/configs/talkgroup_rules.yml.j2
    dest: /opt/{{ dvm_folder }}/configs/talkgroup_rules.yml
  vars:
    talkgroups: "{{ talkgroup_data.groupVoice }}"

- name: Load RID configuration data
  ansible.builtin.include_vars:
    file: "{{ rid_config_file }}"
    name: rid_data

- name: Generate RID configuration from template
  ansible.builtin.template:
    src: templates/configs/rid_acl.dat.j2
    dest: /opt/{{ dvm_folder }}/configs/rid_acl.dat
  vars:
    ridlist: "{{ rid_data.rid_list }}"
