---
- name: Execute Debian or Ubuntu specific tasks
  ansible.builtin.import_tasks: debian.yml

- name: Get and install the DVM binaries
  ansible.builtin.import_tasks: get_install_dvm.yml

- name: Install and configure the DVM Provisioning Manager
  ansible.builtin.import_tasks: install_dvmprov.yml
  when: dvmprov
